//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cache_part")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub cache_entry_id: Uuid,
  pub part_number: i32,
  pub e_tag: String,
  pub size: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::cache_entry::Entity",
    from = "Column::CacheEntryId",
    to = "super::cache_entry::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  CacheEntry,
}

impl Related<super::cache_entry::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::CacheEntry.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
