//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cache_entry")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub repo: String,
  pub key: String,
  pub version: String,
  pub write_isolation_key: String,
  pub size: i64,
  pub created_at: DateTime,
  pub used_at: DateTime,
  pub complete: bool,
  pub file_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
