//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cache_upload_part")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub cache_upload: i32,
  pub part_number: i32,
  pub e_tag: Option<String>,
  pub size: i64,
  pub start_byte: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::cache_upload::Entity",
    from = "Column::CacheUpload",
    to = "super::cache_upload::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  CacheUpload,
}

impl Related<super::cache_upload::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::CacheUpload.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
