//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cache_upload")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub repo: String,
  pub key: String,
  pub version: String,
  pub write_isolation_key: String,
  pub size: Option<i64>,
  pub created_at: DateTime,
  pub s3_upload_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::cache_upload_part::Entity")]
  CacheUploadPart,
}

impl Related<super::cache_upload_part::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::CacheUploadPart.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
