//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cache_entry")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub repo: String,
  pub key: String,
  pub version: String,
  pub write_isolation_key: String,
  pub complete: bool,
  pub size: i64,
  pub created_at: DateTime,
  pub used_at: Option<DateTime>,
  pub s3_upload_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::cache_part::Entity")]
  CachePart,
}

impl Related<super::cache_part::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::CachePart.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
