server:
  connections:
    forgejo:
      url: <url>
      uuid: <uuid>
      token: <token>
runner:
  name: test
  labels:
    - test-latest:docker://catthehacker/ubuntu:act-latest
    - rust-test-latest:docker://catthehacker/ubuntu:rust-latest
    - node-test-latest:docker://catthehacker/ubuntu:js-latest
cache:
  enabled: true
  secret: "test-secret"
  external_server: "http://backend:8000"
